services:
  tg_bot:
    restart: always
    container_name: tg_bot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    dns:
      - 172.16.254.2
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}

  mongodb:
    restart: always
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

networks:
  default:
    name: network
