services:
  tg_bot:
    restart: always
    container_name: tg_bot
    build: .

  mongodb:
    restart: always
    image: mongo:latest-24-02-2025
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

networks:
  default:
    name: network